// import React from "react";
import Pets from "./Pets.jsx";

export const ListTask = [
  {
    id: 1,
    name: "Bull",
    race: "dog",
    type: "Wild Animal",
    location: "Lagos",
    photo: Pets.bull,
    adopted: false,
    price: 130
  },
  {
    price: 135,
    id: 2,
    name: "Goons",
    race: "dog",
    type: "Wild Animal",
    location: "Canada",
    photo: Pets.goon,
    adopted: false,
  },
  {
    adopted: false,
    id: "2a",
    name: "Goons",
    race: "dog",
    type: "Wild Animal",
    location: "Canada",
    photo: Pets.goon,
    price: 150
  },
  {
    id: 3,
    adopted: false,
    name: "Biffy",
    race: "dog",
    type: "Domestic Animal",
    location: "Ibadan Island",
    photo: Pets.biffy,
    price: 290
  },
  {
    id: 4,
    name: "Jack",
    race: "dog",
    type: "Wild Animal",
    location: "Agege Lagos",
    photo: Pets.jack,
    price: 40,
    adopted: false,
  },
  {
    id: 5,
    name: "Bobby",
    race: "dog",
    type: "Domestic Animal",
    location: "Silankatu Finland",
    photo: Pets.bob,
    adopted: false,
    price: 300
  },
  {
    id: 6,
    name: "Mad",
    race: "dog",
    type: "Wild Animal",
    location: "Silankatu Finland",
    photo: Pets.bob,
    adopted: false,
    price: 200
  },

  //   cat race
  {
    price: 135,
    id: 7,
    name: "Elegance",
    race: "cat",
    type: "Wild Animal",
    location: "Lagos island Nigeria",
    photo: Pets.catfat,
    adopted: false,
  },
  {
    id: 8,
    adopted: false,
    name: "Lamin catalogue",
    race: "cat",
    type: "Domestic Animal",
    location: "Silankatu Finland",
    photo: Pets.catolee,
    price: 130,
  },
  {
    id: 9,
    name: "Bobbinson",
    race: "cat",
    type: "Domestic Animal",
    location: "Silankatu  Finland Ayvalta SA",
    photo: Pets.catty,
    adopted: false,
    price: 235,
  },
  {
    id: 10,
    name: "Tinubuntu",
    race: "cat",
    type: "World Animal",
    location: "Idiarere International",
    photo: Pets.catuu,
    adopted: false,
    price: 107,
  },
  {
    id: 11,
    name: "Baderen",
    race: "cat",
    type: "World Animal",
    location: "Idiarere International",
    photo: Pets.catu,
    adopted: false,
    price: 125,
  },

  //   rabbit race

  {
    id: 12,
    name: "Hasher",
    race: "rabbit",
    type: "Wild Animal",
    location: "Ibada Idiarere International",
    photo: Pets.rabbit,
    adopted: false,
    price: 125,
  },
  {
    price: 105,
    id: 13,
    name: "Tufuulern",
    race: "rabbit",
    type: "Domestic Animal",
    location: "Idiarere Ekiti International",
    photo: Pets.rabbito,
    adopted: false,
  },
  {
    price: 135,
    id: 14,
    adopted: false,
    name: "Baggy",
    race: "rabbit",
    type: "Domestic Animal",
    location: "Idiarere International",
    photo: Pets.rabbitua,
  },
  // Mouse race

  {
    id: 15,
    name: "Catalanta",
    race: "Mouse",
    type: "Wild Animal",
    location: "Idiarere International",
    photo: Pets.mouse,
    adopted: false,
    price: 236,
  },
  {
    id: 16,
    name: "Lonputable",
    race: "Mouse",
    type: "Wild Animal",
    location: "Toyo Ibadan foundation",
    photo: Pets.mousee,
    adopted: false,
    price: 142,
  },
  {
    id: 17,
    name: "Fabaska",
    race: "Mouse",
    type: "Domestic Animal",
    location: "Idiarere International",
    photo: Pets.mouseu,
    adopted: false,
    price: 135,
  },
];

console.log(ListTask)